const types = {
  ADD_USER: 'ADD_USER',
  SET_CONTESTANT: 'SET_CONTESTANT',
  MARK_SQUARE: 'MARK_SQUARE',
  CLEAR_BOARD: 'CLEAR_BOARD',
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: 'DELETE_TODO',
  COMPLETE_TODO: 'COMPLETE_TODO',
};

export default types;
